### PR TITLE
Prepare release v2.0.0 

### PR DESCRIPTION
**Pull request by matsumotory**
v2.0.0 feature

- Support some TLS feature like ssl_verify_handler #342
- Support async frame 
  - Add Nginx::Async.sleep
  - Add Nginx::Async.http_client

## Pull-Request Check List

- [x] Add patches into `src/`.
- [x] Add test into `test/`. Please see about [test docs](https://github.com/matsumotory/ngx_mruby/tree/master/docs/test).
- [x] Add docs into `docs/` if you change the features such as [build system](https://github.com/matsumotory/ngx_mruby/tree/master/docs/install), [Ruby methods, class](https://github.com/matsumotory/ngx_mruby/tree/master/docs/class_and_method) and [nginx directives](https://github.com/matsumotory/ngx_mruby/tree/master/docs/directives).

### CODE REVIEW

**Comment by yyamano** [comment]
Random thoughts on v2:

* development timeframe 
* keep backward compatibility?
* v1 branch for maintenance
* Split Nginx::SSL if we have more handler specific methods. #339 and #342

**Comment by matsumotory** [comment]
@yyamano Thank you for your suggestion. What do you mean "development timeframe"?

**Comment by matsumotory** [comment]
We want to release v2.0.0 in April.

**Comment by yyamano** [comment]
@matsumotory I meant development schedule. 

I'd like to have mruby 1.4.1 on both v1 and v2 branches. 
1.4.1 is planned to release around April. See https://github.com/mruby/mruby/issues/3935#issuecomment-363959581

**Comment by matsumotory** [comment]
Removed WIP, so all features were implemented for v2. Ready to v2 release!

**Pull request merged**
