### PR TITLE
Cleanup build system

### PR DESCRIPTION
**Pull request by yyamano**
Simplify our build system. 

## Pull-Request Check List

- [ ] Add patches into `src/`.
- [ ] Add test into `test/`. Please see about [test docs](https://github.com/matsumotory/ngx_mruby/tree/master/docs/test).
- [ ] Add docs into `docs/` if you change the features such as [build system](https://github.com/matsumotory/ngx_mruby/tree/master/docs/install), [Ruby methods, class](https://github.com/matsumotory/ngx_mruby/tree/master/docs/class_and_method) and [nginx directives](https://github.com/matsumotory/ngx_mruby/tree/master/docs/directives).

### CODE REVIEW

**Comment by yyamano** [comment]
@takumakume I'm wondering if you can review the change. I don't think I can test all combination of build options.

**Comment by matsumotory** [comment]
Thank you for your PR. @takumakume Could you review this PR?

**Comment by takumakume** [comment]
@yyamano 

It's great to move complex OpenSSL build stuff into configure and simplify them. Thank you!!
I think the refactoring was successful because it passed all the test items.
LGTM!

> @takumakume I'm wondering if you can review the change. I don't think I can test all combination of build options.

I also agree.
I am the reason you increase the test pattern, it was to prevent the recurrence of the bug.

About testing the `--with-openssl-src` option to build OpenSSL Source.

Currently, we test `BUILD_WITH_OPENSSL_SRC` with multiple Nginx versions. However, it can be reduced because it does not depend on the version of Nginx.

https://github.com/matsumotory/ngx_mruby/blob/08a94c54a9829b58da3f66d8bd84ab99c52bbcc6/.travis.yml#L26-L35

I think it is enough to test only this pattern. (I'm sorry while adding.)

**Comment by yyamano** [comment]
@takumakume Thank you so much for the review. I'd like to keep  current test patterns for now because @Zogoo have been working on  selectable client  cert (#442) and we might have a timing issue as I mentioned at https://github.com/matsumotory/ngx_mruby/pull/457#issuecomment-596345203.

I will rebase the branch and merge it later.  

Thank you again.

**Comment by matsumotory** [comment]
@yyamano @takumakume Thanks always!

**Pull request merged**
