### PR TITLE
[WIP] updates for nginx 1.15.10

### PR DESCRIPTION
**Pull request by sawanoboly**
update to latest mainline and follow changes.

## Pull-Request Check List

- [ ] Add patches into `src/`.
- [ ] Add test into `test/`. Please see about [test docs](https://github.com/matsumotory/ngx_mruby/tree/master/docs/test).
- [ ] Add docs into `docs/` if you change the features such as [build system](https://github.com/matsumotory/ngx_mruby/tree/master/docs/install), [Ruby methods, class](https://github.com/matsumotory/ngx_mruby/tree/master/docs/class_and_method) and [nginx directives](https://github.com/matsumotory/ngx_mruby/tree/master/docs/directives).

### CODE REVIEW

**Comment by sawanoboly** [comment]
@matsumotory Build fails on the latest mainline nginx 1.15.10. Is it possible to fix?

```
/home/travis/build/matsumotory/ngx_mruby/src/http/ngx_http_mruby_server.c: In function ‘ngx_mrb_add_listener’:
/home/travis/build/matsumotory/ngx_mruby/src/http/ngx_http_mruby_server.c:56:29: error: request for member ‘sockaddr’ in something not a structure or union
   ngx_memcpy(&lsopt.sockaddr.sockaddr, &u.sockaddr, u.socklen);
                             ^
src/core/ngx_string.h:106:49: note: in definition of macro ‘ngx_memcpy’
 #define ngx_memcpy(dst, src, n)   (void) memcpy(dst, src, n)
                                                 ^
/home/travis/build/matsumotory/ngx_mruby/src/http/ngx_http_mruby_server.c:88:38: error: request for member ‘sockaddr’ in something not a structure or union
   (void)ngx_sock_ntop(&lsopt.sockaddr.sockaddr, lsopt.socklen, lsopt.addr, NGX_SOCKADDR_STRLEN, 1);
                                      ^
/home/travis/build/matsumotory/ngx_mruby/src/http/ngx_http_mruby_server.c:88:69: error: ‘ngx_http_listen_opt_t’ has no member named ‘addr’
   (void)ngx_sock_ntop(&lsopt.sockaddr.sockaddr, lsopt.socklen, lsopt.addr, NGX_SOCKADDR_STRLEN, 1);
                                                                     ^
make[2]: *** [objs/addon/http/ngx_http_mruby_server.o] Error 1
make[2]: Leaving directory `/home/travis/build/matsumotory/ngx_mruby/build/nginx-1.15.10'
make[1]: *** [build] Error 2
make[1]: Leaving directory `/home/travis/build/matsumotory/ngx_mruby/build/nginx-1.15.10'
make: *** [build_ngx_mruby] Error 2
The command "sh test.sh" exited with 2.
```

**Comment by sawanoboly** [comment]
hmm...

https://github.com/nginx/nginx/compare/release-1.15.9...release-1.15.10#diff-de2d1885ca5c2ea7a5296ce4b6d961daR68

**Comment by sawanoboly** [comment]
ah-..


> /home/travis/build/matsumotory/ngx_mruby/src/http/ngx_http_mruby_server.c:88:69: error: ‘ngx_http_listen_opt_t’ has no member named ‘addr’
>   (void)ngx_sock_ntop(&lsopt.sockaddr.sockaddr, lsopt.socklen, lsopt.addr, NGX_SOCKADDR_STRLEN, 1);

https://github.com/nginx/nginx/compare/release-1.15.9...release-1.15.10#diff-de2d1885ca5c2ea7a5296ce4b6d961daL104

**Comment by sawanoboly** [comment]
```
/home/travis/build/matsumotory/ngx_mruby/src/http/ngx_http_mruby_server.c:93:54: error: passing argument 3 of ‘ngx_sock_ntop’ from incompatible pointer type [-Werror]
   (void)ngx_sock_ntop(lsopt.sockaddr, lsopt.socklen, &lsopt.addr_text, NGX_SOCKADDR_STRLEN, 1);
                                                      ^
In file included from src/core/ngx_core.h:79:0,
                 from /home/travis/build/matsumotory/ngx_mruby/src/http/ngx_http_mruby_module.h:11,
                 from /home/travis/build/matsumotory/ngx_mruby/src/http/ngx_http_mruby_server.c:9:
src/core/ngx_inet.h:114:8: note: expected ‘u_char *’ but argument is of type ‘struct ngx_str_t *’
 size_t ngx_sock_ntop(struct sockaddr *sa, socklen_t socklen, u_char *text,
        ^
```

えー

**Comment by sawanoboly** [comment]
あとは @matsumotory にまかせます。。。

**Comment by matsumotory** [comment]
@sawanoboly Thank you for your trying to fix the compatibility with 1.15.10. I fixed viar #420 .

**Comment by matsumotory** [comment]
This issue was fixed via #420 Thanks!

**Pull request closed without merging**
