### PR TITLE
update test target to 1.13.11

### PR DESCRIPTION
**Pull request by sawanoboly**
just update to latest releases.

## Pull-Request Check List

- [ ] Add patches into `src/`.
- [ ] Add test into `test/`. Please see about [test docs](https://github.com/matsumotory/ngx_mruby/tree/master/docs/test).
- [ ] Add docs into `docs/` if you change the features such as [build system](https://github.com/matsumotory/ngx_mruby/tree/master/docs/install), [Ruby methods, class](https://github.com/matsumotory/ngx_mruby/tree/master/docs/class_and_method) and [nginx directives](https://github.com/matsumotory/ngx_mruby/tree/master/docs/directives).

### CODE REVIEW

**Comment by sawanoboly** [comment]
curl openssl-1.0.2-latest.tar.gz returns 2 pattern ...?

```
$ curl -sfLI https://www.openssl.org/source/openssl-1.0.2-latest.tar.gz 
HTTP/1.1 301 Moved Permanently
Server: Apache/2.4.18 (Ubuntu)
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Location: https://www.openssl.org/source/old/1.0.2/openssl-1.0.2-latest.tar.gz

$ curl -sfLI https://www.openssl.org/source/openssl-1.0.2-latest.tar.gz 
HTTP/1.1 302 Moved Temporarily
Server: Apache/2.4.18 (Ubuntu)
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Location: https://www.openssl.org/source/openssl-1.0.2o.tar.gz
```

**Comment by sawanoboly** [comment]
report https://github.com/openssl/openssl/issues/5865

**Comment by matsumotory** [comment]
fmfm

**Comment by sawanoboly** [comment]
passed by retry 😃

**Comment by matsumotory** [comment]
Thanks!

**Pull request merged**
