### PR TITLE
update test target to 1.17.6 with little changes due to compatibility.

### LINKED ISSUE #438: Build fails with Nginx 1.17.6
https://travis-ci.org/matsumotory/ngx_mruby/builds/614339720

It is a report for the time being.

```
.
.
/home/travis/build/matsumotory/ngx_mruby/src/stream/ngx_stream_mruby_connection.c: In function ‘ngx_stream_mrb_proxy_protocol_addr’:
/home/travis/build/matsumotory/ngx_mruby/src/stream/ngx_stream_mruby_connection.c:205:54: error: ‘ngx_connection_t’ has no member named ‘proxy_protocol_addr’
   return mrb_str_new(mrb, (const char *)s->connection->proxy_protocol_addr.data,
                                                      ^
/home/travis/build/matsumotory/ngx_mruby/src/stream/ngx_stream_mruby_connection.c:206:35: error: ‘ngx_connection_t’ has no member named ‘proxy_protocol_addr’
                      s->connection->proxy_protocol_addr.len);
                                   ^
/home/travis/build/matsumotory/ngx_mruby/src/stream/ngx_stream_mruby_connection.c:207:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
cc1: all warnings being treated as errors
objs/Makefile:1608: recipe for target 'objs/addon/stream/ngx_stream_mruby_connection.o' failed
make[2]: *** [objs/addon/stream/ngx_stream_mruby_connection.o] Error 1
make[2]: Leaving directory '/home/travis/build/matsumotory/ngx_mruby/build/nginx-1.17.6'
Makefile:8: recipe for target 'build' failed
make[1]: *** [build] Error 2
make[1]: Leaving directory '/home/travis/build/matsumotory/ngx_mruby/build/nginx-1.17.6'
Makefile:81: recipe for target 'build_ngx_mruby' failed
make: *** [build_ngx_mruby] Error 2
```

Note:

- [https://github.com/nginx/nginx/compare/release-1.17.5..release-1.17.6](https://github.com/nginx/nginx/compare/release-1.17.5..release-1.17.6)

### PR DESCRIPTION
**Pull request by sawanoboly**
- update test target to 1.17.6
- update proxy_protocol_addr to proxy_protocol.src_addr at `ngx_stream_mrb_proxy_protocol_addr`
  - it resolves #438

## Pull-Request Check List

- [x] Add patches into `src/`.
- [ ] Add test into `test/`. Please see about [test docs](https://github.com/matsumotory/ngx_mruby/tree/master/docs/test).
- [ ] Add docs into `docs/` if you change the features such as [build system](https://github.com/matsumotory/ngx_mruby/tree/master/docs/install), [Ruby methods, class](https://github.com/matsumotory/ngx_mruby/tree/master/docs/class_and_method) and [nginx directives](https://github.com/matsumotory/ngx_mruby/tree/master/docs/directives).

### CODE REVIEW

**Comment by matsumotory** [comment]
Thanks!

**Comment by sawanoboly** [comment]
@matsumotory Could I bump new version as v2.1.8?

**Comment by matsumotory** [comment]
Of cause!

**Comment by sawanoboly** [comment]
done! https://github.com/matsumotory/ngx_mruby/releases/tag/v2.1.8

**Comment by matsumotory** [comment]
Oh! Please include other PR information to release notes from v2.1.7 to v2.1.8!

**Comment by sawanoboly** [comment]
ごめん出かけてしまった…

**Comment by sawanoboly** [comment]
sorry, updated by mobile

**Pull request merged**
