### PR TITLE
Refactoing openssl tests

### PR DESCRIPTION
**Pull request by yyamano**
Introduce OpenSSLTestClient for making debug easier.
You can see output of openssl command if you run the test with DEBUG environment variable.

## Pull-Request Check List

- [ ] Add patches into `src/`.
- [x] Add test into `test/`. Please see about [test docs](https://github.com/matsumotory/ngx_mruby/tree/master/docs/test).
- [ ] Add docs into `docs/` if you change the features such as [build system](https://github.com/matsumotory/ngx_mruby/tree/master/docs/install), [Ruby methods, class](https://github.com/matsumotory/ngx_mruby/tree/master/docs/class_and_method) and [nginx directives](https://github.com/matsumotory/ngx_mruby/tree/master/docs/directives).

### CODE REVIEW

**Comment by yyamano** [comment]
Hmm, really strange. I just did rebase. All tests passed now.

Do we have a timing issue?

https://travis-ci.org/matsumotory/ngx_mruby/jobs/658761896?utm_medium=notification&utm_source=github_status

~~~
Fail: ngx_mruby - ssl certificate changing
 - Assertion[2] Failed: Expected to be equal
    Expected: "1"
      Actual: "-1"
Fail: ngx_mruby - ssl certificate changing using data instead of file
 - Assertion[2] Failed: Expected to be equal
    Expected: "1"
      Actual: "-1"
Fail: ngx_mruby - ssl certificate changing - reading handler from file without caching
 - Assertion[2] Failed: Expected to be equal
    Expected: "1"
      Actual: "-1"
 - Assertion[3] Failed: Expected to be equal
    Expected: "1"
      Actual: "-1"
 - Assertion[4] Failed: Expected to be equal
    Expected: "1"
      Actual: "-1"
Fail: ngx_mruby - ssl certificate changing - reading handler from file with caching
 - Assertion[2] Failed: Expected to be equal
    Expected: "1"
      Actual: "-1"
 - Assertion[4] Failed: Expected to be equal
    Expected: "1"
      Actual: "-1"
Total: 92
   OK: 88
   KO: 4
Crash: 0
 Time: 18.457279 seconds
~~~

**Comment by yyamano** [comment]
@matsumotory Could you merge the pull request?

We might have a timing issue, but I can't reproduce it.
I changed to print openssl debug information if tests failed. Let's see if it works.

**Comment by matsumotory** [comment]
LGTM Thanks!

**Comment by matsumotory** [comment]
For now, all green. Thank you for your investigation and Let's check about the timing issue from now on.

Screenshot 2020-03-10 14 44 28

**Pull request merged**
